// Package status renders .coherence/STATUS.md.
package status

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"coherence/internal/git"
	"coherence/internal/ontology"
	"coherence/internal/report"
	"coherence/internal/rules"
)

// Path returns the canonical STATUS.md path for the given repo root.
func Path(rootDir string) string {
	return filepath.Join(rootDir, ".coherence", "STATUS.md")
}

// Write recomputes and writes STATUS.md. Returns the path written.
func Write(rootDir string, ont *ontology.Ontology) (string, error) {
	last := report.Load(rootDir)
	snapshots := listSnapshots(rootDir)
	live := computeLive(ont, rootDir)
	out := render(ont, last, snapshots, live)
	dst := Path(rootDir)
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(dst, []byte(out), 0o644); err != nil {
		return "", err
	}
	return dst, nil
}

type snapshot struct {
	Date          string
	Verdict       string
	ScenarioCount int
}

var (
	dateDirRe   = regexp.MustCompile(`^\d{4}-\d{2}-\d{2}$`)
	verdictRe   = regexp.MustCompile(`(?im)^- \*\*Suite verdict:\*\*\s*` + "`?" + `([a-z]+)` + "`?")
	tableRowRe  = regexp.MustCompile(`(?m)^\|\s*\d`)
)

func listSnapshots(rootDir string) []snapshot {
	base := filepath.Join(rootDir, ".coherence", "runs")
	entries, err := os.ReadDir(base)
	if err != nil {
		return nil
	}
	out := []snapshot{}
	for _, e := range entries {
		if !e.IsDir() || !dateDirRe.MatchString(e.Name()) {
			continue
		}
		indexPath := filepath.Join(base, e.Name(), "index.md")
		data, err := os.ReadFile(indexPath)
		if err != nil {
			continue
		}
		verdict := "unknown"
		if m := verdictRe.FindStringSubmatch(string(data)); m != nil {
			verdict = strings.ToLower(m[1])
		}
		count := len(tableRowRe.FindAllString(string(data), -1))
		out = append(out, snapshot{Date: e.Name(), Verdict: verdict, ScenarioCount: count})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Date > out[j].Date })
	return out
}

type liveSection struct {
	Range    string
	Files    []string
	Findings []rules.Finding
}

func computeLive(ont *ontology.Ontology, rootDir string) struct {
	Last     liveSection
	Worktree liveSection
} {
	lastFiles := git.DiffNameOnly("HEAD~1..HEAD", rootDir)
	worktreeFiles := git.WorktreeChangedFiles(rootDir)
	return struct {
		Last     liveSection
		Worktree liveSection
	}{
		Last:     liveSection{Range: "HEAD~1..HEAD", Files: lastFiles, Findings: rules.Evaluate(ont, lastFiles)},
		Worktree: liveSection{Files: worktreeFiles, Findings: rules.Evaluate(ont, worktreeFiles)},
	}
}

type counts struct{ err, warn, total int }

func summarize(findings []rules.Finding) counts {
	c := counts{total: len(findings)}
	for _, f := range findings {
		switch f.Severity {
		case "error":
			c.err++
		case "warn":
			c.warn++
		}
	}
	return c
}

func findingsTable(findings []rules.Finding) []string {
	if len(findings) == 0 {
		return []string{"_No findings._"}
	}
	rows := []string{
		"| Severity | Rule | Triggered by |",
		"| --- | --- | --- |",
	}
	for _, f := range findings {
		trig := "—"
		if len(f.TriggeredBy) > 0 {
			limit := f.TriggeredBy
			if len(limit) > 3 {
				limit = limit[:3]
			}
			parts := make([]string, 0, len(limit))
			for _, p := range limit {
				parts = append(parts, "`"+p+"`")
			}
			trig = strings.Join(parts, ", ")
		}
		rows = append(rows, fmt.Sprintf("| %s | `%s` | %s |", f.Severity, f.Rule, trig))
	}
	return rows
}

func render(ont *ontology.Ontology, last *report.Payload, snapshots []snapshot, live struct {
	Last     liveSection
	Worktree liveSection
}) string {
	var lines []string
	push := func(s ...string) { lines = append(lines, s...) }

	push("# Repo Coherence - Current State", "")
	push("_Generated by `coherence status`. Overwritten on each refresh. The rules engine is **diff-based**: it flags transitions (file A changed without file B), not steady-state coherence._", "")
	push("## Repo Coherence — Right Now", "")
	push("_Computed live from the current git state. Rules-only, no LLM pass. Pair this with any project-specific docs or link checks you maintain._", "")

	push(fmt.Sprintf("### Last commit (`%s`)", live.Last.Range), "")
	if len(live.Last.Files) == 0 {
		push("_No files changed in this range._")
	} else {
		s := summarize(live.Last.Findings)
		push(fmt.Sprintf("- Files changed: %d", len(live.Last.Files)))
		push(fmt.Sprintf("- Findings: **%d error**, **%d warn**, %d total", s.err, s.warn, s.total))
		push("")
		push(findingsTable(live.Last.Findings)...)
	}
	push("")

	push("### Working tree (uncommitted vs `HEAD`)", "")
	if len(live.Worktree.Files) == 0 {
		push("_Working tree clean._")
	} else {
		s := summarize(live.Worktree.Findings)
		push(fmt.Sprintf("- Files changed: %d", len(live.Worktree.Files)))
		push(fmt.Sprintf("- Findings: **%d error**, **%d warn**, %d total", s.err, s.warn, s.total))
		push("")
		push(findingsTable(live.Worktree.Findings)...)
	}
	push("")

	push("## Scenario Run History", "")
	push("_Optional scenario snapshots under `.coherence/runs/`. They are separate from the live repository state above._", "")
	if len(snapshots) == 0 {
		push("_No self-test runs recorded yet._")
	} else {
		latest := snapshots[0]
		push(fmt.Sprintf("- Latest run: **%s**, scenarios: %d, self-test verdict: **%s**", latest.Date, latest.ScenarioCount, latest.Verdict))
		push(fmt.Sprintf("- Index: [`.coherence/runs/%s/index.md`](./runs/%s/index.md)", latest.Date, latest.Date))
		if len(snapshots) > 1 {
			push("")
			push("| Date | Self-test verdict | Scenarios | Index |", "| --- | --- | --- | --- |")
			limit := snapshots
			if len(limit) > 10 {
				limit = limit[:10]
			}
			for _, s := range limit {
				push(fmt.Sprintf("| %s | %s | %d | [open](./%s/index.md) |", s.Date, s.Verdict, s.ScenarioCount, s.Date))
			}
		}
	}
	push("")

	push("## Active Rules", "")
	push("| Rule | Severity | When | Expect Any Of |", "| --- | --- | --- | --- |")
	for _, r := range ont.Rules {
		when := bullets(r.When)
		expect := bullets(r.ExpectAny)
		push(fmt.Sprintf("| `%s` | %s | %s | %s |", r.ID, r.Severity, when, expect))
	}
	push("")

	push("## LLM Pass Configuration", "")
	push("- Provider: Groq (OpenAI-compatible Chat Completions endpoint).")
	push("- Default model: `llama-3.3-70b-versatile`; override via `COHERENCE_GROQ_MODEL`.")
	push("- Enable per-run with `COHERENCE_LLM=1` (or `--llm`); requires `GROQ_API_KEY`.")
	push("- Hard cap: 3 calls per commit; findings are always `warn`.", "")

	push("## Last Ephemeral Scan", "")
	push("_This block reflects the most recent `coherence` invocation on this machine (from `.coherence/last-report.json`, gitignored). For substantive run history, see the committed snapshots above._", "")
	if last == nil {
		push("_No `.coherence/last-report.json` on disk yet. Run `coherence scan --staged` or `coherence check` to generate one._")
	} else {
		push(fmt.Sprintf("- Subcommand: `%s`", last.Subcommand))
		push(fmt.Sprintf("- Generated: %s", last.GeneratedAt))
		push(fmt.Sprintf("- Files inspected: %d", len(last.Files)))
		push(fmt.Sprintf("- Rules loaded: %d", last.RuleCount))
		var llmLine string
		if last.LLM.Skipped != nil {
			llmLine = fmt.Sprintf("- LLM: skipped (%s)", *last.LLM.Skipped)
		} else {
			model := ""
			if last.LLM.Model != nil {
				model = *last.LLM.Model
			}
			llmLine = fmt.Sprintf("- LLM: %s, %d call(s)", model, last.LLM.Calls)
		}
		push(llmLine)
		push(fmt.Sprintf("- Findings: %d", len(last.Findings)))
		if len(last.Findings) > 0 {
			push("")
			push("| Severity | Rule | Message |", "| --- | --- | --- |")
			for _, f := range last.Findings {
				msg := strings.ReplaceAll(f.Message, "|", "\\|")
				push(fmt.Sprintf("| %s | `%s` | %s |", f.Severity, f.Rule, msg))
			}
		}
	}
	push("")

	push("## How to refresh this page", "")
	push("```bash")
	push("coherence status                      # rewrite .coherence/STATUS.md")
	push("coherence check                       # dry-run against HEAD~1")
	push("COHERENCE_LLM=1 coherence scan --staged # staged set, with Groq pass")
	push("```", "")

	return strings.Join(lines, "\n")
}

func bullets(items []string) string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return strings.Join(out, ", ")
}
