package adversarial

import "github.com/fireharp/coherence/internal/graph"

func builtinDeterministicSpecsB() []Spec {
	return []Spec{
		{
			ID:                      "ADV-011-dependency-cycle",
			Description:             "Close a Go import cycle across package directories.",
			Operation:               opReplaceText,
			TargetKinds:             []graph.NodeKind{graph.NodeFile},
			ExpectedMeters:          []string{"dependency_cycles"},
			AllowedSideEffectMeters: []string{"callsite_blast_radius"},
			Selector:                Selector{PathGlob: "internal/c/c.go"},
			Edit: Edit{
				Old: "package c\n\nfunc C() {}\n",
				New: "package c\n\nimport \"example.com/adversarial/internal/a\"\n\nfunc C() { a.A() }\n",
			},
		},
		{
			ID:                      "ADV-012-unimplemented-story",
			Description:             "Add a user story in a repo that already uses implements annotations.",
			Operation:               opAddFile,
			TargetKinds:             []graph.NodeKind{graph.NodeUserStory},
			ExpectedMeters:          []string{"unimplemented_stories"},
			Selector:                Selector{IDPrefix: "us:US-001"},
			AllowedSideEffectMeters: []string{"trace_coverage", "path_loss"},
			Edit:                    Edit{Path: "docs/user-stories/US-002.md", Content: "---\nid: US-002\n---\n# US-002 Future story\n\nRelated to [US-001](US-001.md).\n"},
		},
		{
			ID:                      "ADV-013-semantic-movement",
			Description:             "Change markdown semantics, not just spelling.",
			Operation:               opAppendText,
			TargetKinds:             []graph.NodeKind{graph.NodeDoc},
			ExpectedMeters:          []string{"semantic_movement"},
			AllowedSideEffectMeters: []string{"truth_alignment"},
			Selector:                Selector{PathGlob: "docs/specs/feature.md"},
			Edit:                    Edit{Text: "\n## Added Semantic Requirement\n\n- Must emit audit evidence for every export.\n"},
		},
		{
			ID:             "ADV-014-semantic-noop-typo",
			Description:    "Apply a typo-only markdown change that should not fire semantic movement.",
			Operation:      opReplaceText,
			TargetKinds:    []graph.NodeKind{graph.NodeDoc},
			ExpectedMeters: []string{},
			Selector:       Selector{PathGlob: "docs/ref/target.md"},
			Edit:           Edit{Old: "reference target", New: "refernece target"},
		},
		{
			ID:             "ADV-015-neighborhood-drift",
			Description:    "Add a linked document that changes graph topology.",
			Operation:      opAddFile,
			TargetKinds:    []graph.NodeKind{graph.NodeDirectory},
			ExpectedMeters: []string{"neighborhood_drift"},
			Selector:       Selector{IDPrefix: "dir:docs"},
			Edit:           Edit{Path: "docs/ref/new-neighbor.md", Content: "# New Neighbor\n\nSee [US-001](../user-stories/US-001.md) and [ADR-001](../decisions/ADR-001.md).\n"},
		},
		{
			ID:                      "ADV-016-blast-radius",
			Description:             "Add a hub doc linked to many existing artifacts.",
			Operation:               opAddFile,
			TargetKinds:             []graph.NodeKind{graph.NodeDirectory},
			ExpectedMeters:          []string{"blast_radius"},
			AllowedSideEffectMeters: []string{"neighborhood_drift", "semantic_movement", "truth_alignment"},
			Selector:                Selector{IDPrefix: "dir:docs"},
			Edit:                    Edit{Path: "docs/hub.md", Content: blastHubContent()},
		},
		{
			ID:             "ADV-017-staleness",
			Description:    "Backdate the temp baseline so staleness fires.",
			Operation:      opBackdateHead,
			TargetKinds:    []graph.NodeKind{graph.NodeFile},
			ExpectedMeters: []string{"staleness"},
			Selector:       Selector{PathGlob: "AGENTS.md"},
			Edit:           Edit{AgeDays: 120},
		},
		{
			ID:                      "ADV-018-callsite-blast-radius",
			Description:             "Change a called Go function with native callsite blast enabled.",
			Operation:               opReplaceText,
			TargetKinds:             []graph.NodeKind{graph.NodeFile},
			ExpectedMeters:          []string{"callsite_blast_radius"},
			AllowedSideEffectMeters: []string{"stale_tests", "truth_alignment"},
			Selector:                Selector{PathGlob: "pkg/policy/policy.go"},
			SkipConditions:          SkipConditions{RequireOptionalEngines: []string{"callsite_blast_radius"}},
			Edit:                    Edit{Old: "return threshold(score)", New: "return threshold(score) && score != 13"},
		},
		{
			ID:                      "ADV-019-dead-code",
			Description:             "Add an unexported Go function with no inbound calls.",
			Operation:               opAppendText,
			TargetKinds:             []graph.NodeKind{graph.NodeFile},
			ExpectedMeters:          []string{"dead_code"},
			AllowedSideEffectMeters: []string{"callsite_blast_radius", "stale_tests", "truth_alignment"},
			Selector:                Selector{PathGlob: "pkg/policy/policy.go"},
			SkipConditions:          SkipConditions{RequireOptionalEngines: []string{"dead_code"}},
			Edit:                    Edit{Text: "\nfunc orphanedBenchHelper() string { return \"unused\" }\n"},
		},
		{
			ID:             "ADV-021-broken-implements-chain",
			Description:    "Remove evidence supporting an implemented story.",
			Operation:      opRemoveFile,
			TargetKinds:    []graph.NodeKind{graph.NodeEvidence},
			ExpectedMeters: []string{"broken_implements_chains"},
			Selector:       Selector{IDPrefix: "evidence:us-001"},
			Edit:           Edit{Path: "docs/evidence/US-001/proof.md"},
		},
	}
}
